### ISSUE TITLE
Win32 Build

### ISSUE THREAD

**Issue by IniTyoo** [heysurfer/Growtopia-Proxy#10]
Hey i have problm it ssay
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'Release\callbacks.obj'	Growtopia Proxy	D:\Desktop\Growtopia-Proxy-main\Main\LINK	1

**Comment by heysurfer** [comment]
Try clean solution If that doesn't work, try creating a new build
https://learn.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application?source=recommendations&view=vs-2022
