### ISSUE TITLE
serverhandle.h build error

### ISSUE THREAD

**Issue by Teruhashi12** [heysurfer/Growtopia-Proxy#14]
for (auto &x : callBack_CALL_FUNCTION)
	{
		if (x.second.target_Case == varlist[0].get_string()  && x.second.enabled)
		{
			for (int i = 1; i < C_MAX_VARIANT_LIST_PARMS; i++) {
				if (varlist[i].get_type() == variant_t::vartype_t::TYPE_STRING && varlist[i].get_string().find(x.second.target_String) != std::string::npos)
				{
					std::string DialogContent = varlist[i].get_string();
					x.second.Timeout = std::chrono::system_clock::now() ;
					if (!x.second.target_Function(DialogContent))
					{
						varlist[i] = DialogContent;
						m_Info->ENetManager->sendPacket(varlist);
					}ü
          
					return true;
				}
			}
		}
	}
	return false;
};

in here error

**Comment by vollehax** [comment]
lol delete the weird "u" letter from the code
also why this have so many detections
https://www.virustotal.com/gui/file/f7bb7db58e92cd42d656e06c58788e8b2d53c8ab75456592b866fa3ba676003d?nocache=1

**Comment by vollehax** [comment]
![image](https://user-images.githubusercontent.com/86126155/233803727-29454fc2-d774-40d4-9a3b-3e7960ca593a.png)
are you stupid? lol

**Comment by vollehax** [comment]
![image](https://user-images.githubusercontent.com/86126155/233803773-b81144ea-9e95-40c7-8120-956b9705f613.png)
if ur so stupid u cant even image from the pic

**Comment by Teruhashi12** [comment]
i

> ![image](https://user-images.githubusercontent.com/86126155/233803773-b81144ea-9e95-40c7-8120-956b9705f613.png) if ur so stupid u cant even image from the pic

i done delete the u but still cant build

**Comment by vollehax** [comment]
then go visual studio settings and change c++ language to 20

**Comment by Teruhashi12** [comment]
> then go visual studio settings and change c++ language to 20

no still cannot build,i done use c++ language still got error like this
![3](https://user-images.githubusercontent.com/90950171/233840149-e9fb4187-49dd-4216-a443-2c9ccb77416d.PNG)
![4](https://user-images.githubusercontent.com/90950171/233840152-c8cde102-a2c9-47cd-960a-78c66ada3b79.PNG)
![5](https://user-images.githubusercontent.com/90950171/233840154-c7b81718-3075-4623-9e6d-9bafdafcac23.PNG)

**Comment by heysurfer** [comment]
https://github.com/heysurfer/Growtopia-Proxy/pull/16
