### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by caycun** [heysurfer/Growtopia-Proxy#3]
can u teach me how to use this in windows?

**Comment by Zeeetu** [comment]
install vs 2022
clone project (can be done through vs)
open in vs (.sln file)
watch video in readme
custom commands in ServerHandle.h
build (ctrl+shift+b)

**Comment by caycun** [comment]
no video in readme, after I build what do I do?

**Comment by Nataaniel** [comment]
> install vs 2022 clone project (can be done through vs) open in vs (.sln file) watch video in readme custom commands in ServerHandle.h build (ctrl+shift+b)

where is video in readme
