### ISSUE TITLE
How do i modify talkbuble text?

### ISSUE THREAD

**Issue by LackFos** [heysurfer/Growtopia-Proxy#30]
variantlist_t var{ "OnTalkBubble" };
			var[2] = "FAKE" + var[2].get_string();
			m_Info->ENetManager->sendPacket(var);
			return true;
this wont work

**Comment by DaughtersOfNyx** [comment]
You are correct, that will not work.

**Comment by DaughtersOfNyx** [comment]
This will work though:

callbackStruct _talkCallback1;
_talkCallback1.target_Case = ("OnTalkBubble");
_talkCallback1.target_String = ("_player_chat=");
_talkCallback1.target_Function = [=](std::string& Dialog)
{
	utils::ReplaceAll(Dialog, "_player_chat=", "_player_chat=FAKE");
	return false;
};
_talkCallback1.infinity = true;
callBack_CALL_FUNCTION[fnv32("replace_Chat1")] = _talkCallback1;

callbackStruct _talkCallback2;
_talkCallback2.target_Case = ("OnTalkBubble");
_talkCallback2.target_String = ("OID:_");
_talkCallback2.target_Function = [=](std::string& Dialog)
{
	utils::ReplaceAll(Dialog, "OID:_", "OID:_FAKE");
	return false;
};
_talkCallback2.infinity = true;
callBack_CALL_FUNCTION[fnv32("replace_Chat2")] = _talkCallback2;
