### ISSUE TITLE
Player data not being updated.

### ISSUE THREAD

**Issue by zix3r** [heysurfer/Growtopia-Proxy#31]
For example, if I join a world, my player info is saved in m_Info->World->Players[myNetId], bla bla.
But if i move or anything, the pos doesn't change, anyway to make it update constantly? So I can get my current local player pos?

**Comment by heysurfer** [comment]
![image](https://github.com/heysurfer/Growtopia-Proxy/assets/58826689/17205661-16c4-4e7f-8a08-09ca5e8ec44c)

example code for updating local position

**Comment by zix3r** [comment]
yo bro, can you add me on dc?
its zix3r
