### ISSUE TITLE
How to implement something like cd?

### ISSUE THREAD

**Issue by Zeeetu** [heysurfer/Growtopia-Proxy#4]
Ex. "!cd 501" drops 5dl and 1wl
Also, how to send dl to wl conversion packet? If possible

**Comment by heysurfer** [comment]
check the example its like cd
https://github.com/heysurfer/Growtopia-Proxy/blob/main/Class/ServerHandle.h#L59

```c++
GameUpdatePacket packet{ };
packet.type = PACKET_ITEM_ACTIVATE_REQUEST;
packet.int_data = 242; //convert to dl
m_Info->ENetManager->sendPacket(packet, getType::Growtopia);
```
